#!/usr/bin/env bash
# Check to support tty.
if [ "$(tty>/dev/null;echo $?)" != "0" ];then
    DOCKERCOMPOSE_EXEC="docker-compose exec -T"
else
    DOCKERCOMPOSE_EXEC="docker-compose exec"
fi
$DOCKERCOMPOSE_EXEC web /bin/ash -c "$*"